# -*- coding: utf-8 -*-
"""Preset management for Audio Spectrum Overlay Maker."""
from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from typing import Any, Dict, List

CUSTOM_LABEL = "カスタム"

COMMON_VALUES: dict[str, Any] = {
    "width": 720,
    "height": 280,
    "fps": 30,
    "bars": 64,
    "display_mode": "片側バー",
    "scroll_mode": "なし",
    "scroll_step_frames": 2,
    "background_color": "#000000",
    "bar_color": "#FFFFFF",
    "bar_color2": "#FFFFFF",
    "color_mode": "縦グラデーション",
    "bar_width_percent": 62,
    "corner_radius": 18,
    "digital_enabled": False,
    "digital_segments": 16,
    "digital_gap_px": 2,
    "edge_glow_enabled": False,
    "edge_glow_percent": 20,
    "peak_hold_enabled": False,
    "peak_hold_ms": 100,
    "peak_decay_ms": 300,
    "peak_size_percent": 4,
    "digital_peak_segments": 1,
    "max_height_percent": 78,
    "side_margin_percent": 5,
    "bottom_margin_percent": 8,
    "frequency_mode": "自動",
    "freq_min": 80.0,
    "freq_max": 12000.0,
    "response_speed": "標準",
    "bounce_strength": "標準",
    "sensitivity_level": "標準",
    "motion_detail": "標準",
    "contrast_profile": "標準",
    "advanced_custom": False,
    "gain_db": 8.0,
    "auto_preview_segment": True,
    "scan_seconds": 120.0,
    "preview_start": 0.0,
    "motion_preview_duration": 10.0,
    "preview_duration": 30.0,
    "warmup": 5.0,
    "sample_rate": 24000,
    "fft_size": 1024,
    "analysis_bands": 128,
    "min_db": -60.0,
    "max_db": -6.0,
    "attack": 0.95,
    "release": 0.75,
    "relative_range_db": 30.0,
    "peak_percentile": 90.0,
    "base_cut": 0.12,
    "pulse_amount": 0.80,
    "pulse_speed": 0.25,
    "gamma": 0.85,
    "post_transform_type": "None",
    "post_transform_rotate_degrees": 0.0,
    "post_transform_scale_percent": 100,
    "post_transform_audio_scale_enabled": False,
    "post_transform_audio_scale_max_percent": 115,
    "post_transform_audio_scale_low_only": True,
    "post_transform_audio_scale_low_band_percent": 25,
    "post_transform_audio_scale_floor_percent": 10,
    "post_transform_audio_scale_ceiling_percent": 50,
    "post_transform_audio_scale_hold_ms": 66,
    "post_transform_audio_scale_decay_ms": 167,
    "post_transform_trapezoid_vertical_percent": 0,
    "post_transform_trapezoid_horizontal_percent": 0,
    "post_transform_trapezoid_top_percent": 100,
    "post_transform_trapezoid_bottom_percent": 100,
    "crf": 18,
    "encoder": "libx264",
    "x264_preset": "veryfast",
}


def _system_preset(name: str, description: str, overrides: dict[str, Any]) -> dict[str, Any]:
    values = deepcopy(COMMON_VALUES)
    values.update(overrides)
    return {
        "name": name,
        "system": True,
        "description": description,
        "values": values,
    }


SYSTEM_PRESETS: list[dict[str, Any]] = [
    _system_preset(
        "01 Basic White",
        "Default white single-bar spectrum for safe overlay compositing.",
        {
            "display_mode": "片側バー",
            "bar_color": "#FFFFFF",
            "bar_color2": "#FFFFFF",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 62,
            "corner_radius": 18,
            "digital_enabled": False,
            "max_height_percent": 78,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "標準",
            "fft_size": 1024,
            "analysis_bands": 128,
            "attack": 0.95,
            "release": 0.75,
            "relative_range_db": 30.0,
            "base_cut": 0.12,
            "pulse_amount": 0.80,
            "pulse_speed": 0.25,
            "gamma": 0.85,
        },
    ),
    _system_preset(
        "02 Dual White",
        "White dual-sided spectrum expanding from the center line.",
        {
            "display_mode": "両側バー",
            "bar_color": "#FFFFFF",
            "bar_color2": "#FFFFFF",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 62,
            "corner_radius": 18,
            "digital_enabled": False,
            "max_height_percent": 84,
            "bottom_margin_percent": 0,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "標準",
            "fft_size": 1024,
            "analysis_bands": 128,
            "attack": 0.95,
            "release": 0.75,
            "relative_range_db": 30.0,
            "base_cut": 0.12,
            "pulse_amount": 0.80,
            "pulse_speed": 0.25,
            "gamma": 0.85,
        },
    ),
    _system_preset(
        "03 Blue Gradient",
        "Calm blue vertical gradient for modern music videos.",
        {
            "display_mode": "片側バー",
            "bar_color": "#00E5FF",
            "bar_color2": "#245CFF",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 62,
            "corner_radius": 18,
            "digital_enabled": False,
            "max_height_percent": 78,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "標準",
            "fft_size": 1024,
            "analysis_bands": 128,
            "attack": 0.95,
            "release": 0.75,
            "relative_range_db": 30.0,
            "base_cut": 0.12,
            "pulse_amount": 0.80,
            "pulse_speed": 0.25,
            "gamma": 0.85,
        },
    ),
    _system_preset(
        "04 Neon Dual",
        "Bright dual-sided neon gradient for high-impact visuals.",
        {
            "display_mode": "両側バー",
            "bar_color": "#00F0FF",
            "bar_color2": "#FF2BD6",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 64,
            "corner_radius": 16,
            "digital_enabled": False,
            "peak_hold_enabled": True,
            "max_height_percent": 86,
            "bottom_margin_percent": 0,
            "response_speed": "速い",
            "bounce_strength": "大きい",
            "sensitivity_level": "標準",
            "motion_detail": "細かい",
            "contrast_profile": "メリハリ",
            "fft_size": 512,
            "analysis_bands": 128,
            "attack": 1.00,
            "release": 0.85,
            "relative_range_db": 28.0,
            "base_cut": 0.16,
            "pulse_amount": 0.90,
            "pulse_speed": 0.35,
            "gamma": 0.85,
        },
    ),
    _system_preset(
        "05 Scrolling Spectrum",
        "Band-gradient spectrum with integer frequency scrolling.",
        {
            "display_mode": "片側バー",
            "bar_color": "#00FF66",
            "bar_color2": "#FF4A00",
            "color_mode": "ループ帯域グラデーション",
            "scroll_mode": "左",
            "scroll_step_frames": 2,
            "bar_width_percent": 62,
            "corner_radius": 18,
            "digital_enabled": False,
            "peak_hold_enabled": True,
            "max_height_percent": 80,
            "response_speed": "速い",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "細かい",
            "contrast_profile": "メリハリ",
            "fft_size": 512,
            "analysis_bands": 128,
            "attack": 1.00,
            "release": 0.78,
            "relative_range_db": 29.0,
            "base_cut": 0.14,
            "pulse_amount": 0.85,
            "pulse_speed": 0.32,
            "gamma": 0.84,
        },
    ),
    _system_preset(
        "06 Smooth Ambient",
        "Softer motion for long-form, lo-fi, ambient, and ballad videos.",
        {
            "display_mode": "片側バー",
            "bar_color": "#B8E7FF",
            "bar_color2": "#6C63FF",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 58,
            "corner_radius": 18,
            "digital_enabled": False,
            "max_height_percent": 66,
            "response_speed": "ゆったり",
            "bounce_strength": "控えめ",
            "sensitivity_level": "標準",
            "motion_detail": "なめらか",
            "contrast_profile": "フラット",
            "fft_size": 2048,
            "analysis_bands": 96,
            "attack": 0.85,
            "release": 0.55,
            "relative_range_db": 34.0,
            "base_cut": 0.10,
            "pulse_amount": 0.65,
            "pulse_speed": 0.18,
            "gamma": 0.88,
        },
    ),
    _system_preset(
        "07 Digital LED",
        "Classic segmented LED-style spectrum with green-to-red vertical coloring.",
        {
            "display_mode": "片側バー",
            "bar_color": "#00D000",
            "bar_color2": "#FF0000",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 74,
            "corner_radius": 0,
            "bars": 32,
            "digital_enabled": True,
            "digital_segments": 16,
            "digital_gap_px": 2,
            "peak_hold_enabled": True,
            "max_height_percent": 82,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "メリハリ",
            "fft_size": 1024,
            "analysis_bands": 128,
            "attack": 0.95,
            "release": 0.75,
            "relative_range_db": 30.0,
            "base_cut": 0.12,
            "pulse_amount": 0.80,
            "pulse_speed": 0.25,
            "gamma": 0.85,
        },
    ),
    _system_preset(
        "08 Digital Dual",
        "Dual-sided segmented digital spectrum.",
        {
            "display_mode": "両側バー",
            "bar_color": "#00D0FF",
            "bar_color2": "#FFFFFF",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "bar_width_percent": 74,
            "corner_radius": 0,
            "bars": 32,
            "digital_enabled": True,
            "digital_segments": 16,
            "digital_gap_px": 1,
            "peak_hold_enabled": True,
            "max_height_percent": 88,
            "bottom_margin_percent": 0,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "メリハリ",
            "fft_size": 1024,
            "analysis_bands": 128,
            "attack": 0.95,
            "release": 0.75,
            "relative_range_db": 30.0,
            "base_cut": 0.12,
            "pulse_amount": 0.80,
            "pulse_speed": 0.25,
            "gamma": 0.85,
        },
    ),
    _system_preset(
        "09 Digital Neon Scroll",
        "Segmented digital spectrum with neon band-gradient scrolling.",
        {
            "display_mode": "片側バー",
            "bar_color": "#00FFAA",
            "bar_color2": "#FF2BD6",
            "color_mode": "ループ帯域グラデーション",
            "scroll_mode": "右",
            "scroll_step_frames": 2,
            "bar_width_percent": 74,
            "corner_radius": 0,
            "bars": 32,
            "digital_enabled": True,
            "digital_segments": 16,
            "digital_gap_px": 2,
            "peak_hold_enabled": True,
            "max_height_percent": 84,
            "response_speed": "速い",
            "bounce_strength": "大きい",
            "sensitivity_level": "高め",
            "motion_detail": "細かい",
            "contrast_profile": "メリハリ",
            "fft_size": 512,
            "analysis_bands": 128,
            "attack": 1.00,
            "release": 0.85,
            "relative_range_db": 28.0,
            "base_cut": 0.16,
            "pulse_amount": 0.90,
            "pulse_speed": 0.35,
            "gamma": 0.84,
        },
    ),
    _system_preset(
        "10 Trapezoid Neon",
        "Neon digital spectrum with vertical trapezoid post transform.",
        {
            "width": 720,
            "height": 280,
            "fps": 30,
            "bars": 32,
            "display_mode": "片側バー",
            "color_mode": "縦グラデーション",
            "scroll_mode": "なし",
            "scroll_step_frames": 2,
            "background_color": "#000000",
            "bar_color": "#8000FF",
            "bar_color2": "#FF8080",
            "bar_width_percent": 74,
            "corner_radius": 2,
            "digital_enabled": True,
            "digital_segments": 16,
            "digital_gap_px": 1,
            "peak_hold_enabled": True,
            "peak_hold_ms": 100,
            "peak_decay_ms": 300,
            "peak_size_percent": 4,
            "digital_peak_segments": 1,
            "max_height_percent": 84,
            "side_margin_percent": 5,
            "bottom_margin_percent": 8,
            "frequency_mode": "自動",
            "freq_min": 80,
            "freq_max": 12000,
            "response_speed": "速い",
            "bounce_strength": "大きい",
            "sensitivity_level": "高め",
            "motion_detail": "細かい",
            "contrast_profile": "メリハリ",
            "advanced_custom": False,
            "gain_db": 12,
            "sample_rate": 24000,
            "fft_size": 512,
            "analysis_bands": 96,
            "min_db": -60,
            "max_db": -6,
            "attack": 1,
            "release": 0.91,
            "relative_range_db": 24,
            "peak_percentile": 92,
            "base_cut": 0.2,
            "pulse_amount": 0.87,
            "pulse_speed": 0.39999999999999997,
            "gamma": 0.8,
            "post_transform_type": "None",
            "post_transform_rotate_degrees": 0,
            "post_transform_trapezoid_vertical_percent": -50,
            "post_transform_trapezoid_horizontal_percent": 0,
            "post_transform_scale_percent": 100,
            "post_transform_audio_scale_max_percent": 100,
            "post_transform_audio_scale_low_only": True,
            "post_transform_audio_scale_low_band_percent": 25,
            "post_transform_audio_scale_floor_percent": 10,
            "post_transform_audio_scale_ceiling_percent": 50,
            "post_transform_audio_scale_hold_ms": 66,
            "post_transform_audio_scale_decay_ms": 167,
            "post_transform_trapezoid_top_percent": 100,
            "post_transform_trapezoid_bottom_percent": 100,
            "crf": 18,
            "encoder": "libx264",
            "x264_preset": "veryfast",
            "post_transform_audio_scale_enabled": False,
        },
    ),
    _system_preset(
        "11 Vertical Scroll",
        "Rotated vertical dual spectrum with scrolling band gradient.",
        {
            "width": 720,
            "height": 720,
            "fps": 30,
            "bars": 64,
            "display_mode": "両側バー",
            "color_mode": "ループ帯域グラデーション",
            "scroll_mode": "右",
            "scroll_step_frames": 2,
            "background_color": "#000000",
            "bar_color": "#666666",
            "bar_color2": "#FFFFFF",
            "bar_width_percent": 62,
            "corner_radius": 0,
            "digital_enabled": False,
            "digital_segments": 16,
            "digital_gap_px": 2,
            "peak_hold_enabled": True,
            "peak_hold_ms": 100,
            "peak_decay_ms": 300,
            "peak_size_percent": 4,
            "digital_peak_segments": 1,
            "max_height_percent": 84,
            "side_margin_percent": 5,
            "bottom_margin_percent": 30,
            "frequency_mode": "自動",
            "freq_min": 80,
            "freq_max": 12000,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "標準",
            "advanced_custom": False,
            "gain_db": 8,
            "sample_rate": 24000,
            "fft_size": 1024,
            "analysis_bands": 64,
            "min_db": -60,
            "max_db": -6,
            "attack": 0.95,
            "release": 0.73,
            "relative_range_db": 30,
            "peak_percentile": 90,
            "base_cut": 0.12,
            "pulse_amount": 0.76,
            "pulse_speed": 0.25,
            "gamma": 0.85,
            "post_transform_type": "None",
            "post_transform_rotate_degrees": -90,
            "post_transform_trapezoid_vertical_percent": 0,
            "post_transform_trapezoid_horizontal_percent": 0,
            "post_transform_scale_percent": 100,
            "post_transform_audio_scale_max_percent": 100,
            "post_transform_audio_scale_low_only": True,
            "post_transform_audio_scale_low_band_percent": 25,
            "post_transform_audio_scale_floor_percent": 10,
            "post_transform_audio_scale_ceiling_percent": 50,
            "post_transform_audio_scale_hold_ms": 66,
            "post_transform_audio_scale_decay_ms": 167,
            "post_transform_trapezoid_top_percent": 100,
            "post_transform_trapezoid_bottom_percent": 100,
            "crf": 18,
            "encoder": "libx264",
            "x264_preset": "veryfast",
            "post_transform_audio_scale_enabled": False,
        },
    ),
    _system_preset(
        "12 Pulsating LED Scroll",
        "Digital scrolling spectrum with audio-reactive scale pulse.",
        {
            "width": 720,
            "height": 280,
            "fps": 30,
            "bars": 32,
            "display_mode": "片側バー",
            "color_mode": "ループ帯域グラデーション",
            "scroll_mode": "左",
            "scroll_step_frames": 2,
            "background_color": "#000000",
            "bar_color": "#FFFF00",
            "bar_color2": "#FF80FF",
            "bar_width_percent": 90,
            "corner_radius": 0,
            "digital_enabled": True,
            "digital_segments": 16,
            "digital_gap_px": 2,
            "peak_hold_enabled": True,
            "peak_hold_ms": 100,
            "peak_decay_ms": 300,
            "peak_size_percent": 4,
            "digital_peak_segments": 1,
            "max_height_percent": 75,
            "side_margin_percent": 8,
            "bottom_margin_percent": 12,
            "frequency_mode": "自動",
            "freq_min": 80,
            "freq_max": 12000,
            "response_speed": "標準",
            "bounce_strength": "標準",
            "sensitivity_level": "標準",
            "motion_detail": "標準",
            "contrast_profile": "メリハリ",
            "advanced_custom": False,
            "gain_db": 8,
            "sample_rate": 24000,
            "fft_size": 1024,
            "analysis_bands": 64,
            "min_db": -60,
            "max_db": -6,
            "attack": 0.95,
            "release": 0.74,
            "relative_range_db": 26,
            "peak_percentile": 92,
            "base_cut": 0.16,
            "pulse_amount": 0.77,
            "pulse_speed": 0.25,
            "gamma": 0.8,
            "post_transform_type": "None",
            "post_transform_rotate_degrees": 0,
            "post_transform_trapezoid_vertical_percent": 0,
            "post_transform_trapezoid_horizontal_percent": 0,
            "post_transform_scale_percent": 100,
            "post_transform_audio_scale_max_percent": 115,
            "post_transform_audio_scale_low_only": True,
            "post_transform_audio_scale_low_band_percent": 25,
            "post_transform_audio_scale_floor_percent": 15,
            "post_transform_audio_scale_ceiling_percent": 50,
            "post_transform_audio_scale_hold_ms": 66,
            "post_transform_audio_scale_decay_ms": 167,
            "post_transform_trapezoid_top_percent": 100,
            "post_transform_trapezoid_bottom_percent": 100,
            "crf": 18,
            "encoder": "libx264",
            "x264_preset": "veryfast",
            "post_transform_audio_scale_enabled": True,
        },
    ),
]


def _blank_user_file(path: Path) -> None:
    path.write_text(json.dumps([], ensure_ascii=False, indent=2), encoding="utf-8")


class PresetManager:
    def __init__(self, user_file: Path) -> None:
        self.user_file = Path(user_file)
        self.user_presets: list[dict[str, Any]] = []
        self.load()

    def load(self) -> None:
        if not self.user_file.exists():
            self.user_file.parent.mkdir(parents=True, exist_ok=True)
            _blank_user_file(self.user_file)
            self.user_presets = []
            return
        try:
            data = json.loads(self.user_file.read_text(encoding="utf-8"))
            if isinstance(data, list):
                self.user_presets = [p for p in data if isinstance(p, dict) and "name" in p and "values" in p]
            else:
                self.user_presets = []
        except Exception:
            backup = self.user_file.with_suffix(".broken.json")
            try:
                self.user_file.replace(backup)
            except Exception:
                pass
            _blank_user_file(self.user_file)
            self.user_presets = []

    def save(self) -> None:
        self.user_file.parent.mkdir(parents=True, exist_ok=True)
        self.user_file.write_text(json.dumps(self.user_presets, ensure_ascii=False, indent=2), encoding="utf-8")

    def all_presets(self) -> list[dict[str, Any]]:
        return deepcopy(SYSTEM_PRESETS) + deepcopy(self.user_presets)

    def names(self) -> list[str]:
        return [p["name"] for p in self.all_presets()]

    def get(self, name: str) -> dict[str, Any] | None:
        for p in self.all_presets():
            if p.get("name") == name:
                return deepcopy(p)
        return None

    def is_system(self, name: str) -> bool:
        p = self.get(name)
        return bool(p and p.get("system"))

    def upsert_user_preset(self, name: str, values: dict[str, Any]) -> None:
        name = name.strip()
        if not name:
            raise ValueError("プリセット名が空です。")
        if self.is_system(name):
            raise ValueError("システムプリセットと同じ名前では保存できません。")
        for p in self.user_presets:
            if p.get("name") == name:
                p["values"] = deepcopy(values)
                p["system"] = False
                self.save()
                return
        self.user_presets.append({"name": name, "system": False, "description": "", "values": deepcopy(values)})
        self.save()

    def delete_user_preset(self, name: str) -> bool:
        if self.is_system(name):
            raise ValueError("システムプリセットは削除できません。")
        before = len(self.user_presets)
        self.user_presets = [p for p in self.user_presets if p.get("name") != name]
        changed = len(self.user_presets) != before
        if changed:
            self.save()
        return changed

    def first_system_values(self) -> dict[str, Any]:
        return deepcopy(SYSTEM_PRESETS[0]["values"])
